language: cpp

services:
  - docker

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    env:
      - ARCH=armhf

script:
  - docker build -t chrmod/snap-mosh .
  - docker run -v $(pwd):$(pwd) -w $(pwd) -t chrmod/snap-mosh sh -c
    "snapcraft --target-arch=${ARCH}"

after_success:
  - openssl aes-256-cbc -K $encrypted_2d29d34bd5be_key -iv $encrypted_2d29d34bd5be_iv
    -in .snapcraft/travis_snapcraft.cfg
    -out .snapcraft/snapcraft.cfg -d

deploy:
  provider: script
  script: docker run -v $(pwd):$(pwd) -w $(pwd) -t chrmod/snap-mosh sh -c
    "snapcraft push *.snap --release edge --target-arch=${ARCH}"
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
