name: weechat-armhf
version: '1.7.1'
summary: Weechat Snap for Raspberrypi
description: |
  The extensible chat client.

grade: devel
confinement: devmode

apps:
  weechat:
    command: weechat

parts:
  weechat:
    plugin: x-cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DOPTION_ENABLE_IRC=on
      - -DENABLE_PYTHON=off
    source: https://github.com/weechat/weechat/archive/v1.7.1.tar.gz
    stage-packages:
      - libcurl3-gnutls
