name: weechat-armhf
version: '1.7.1'
summary: Weechat Snap for Raspberrypi
description: |
  The extensible chat client.

grade: devel
confinement: devmode

apps:
  weechat:
    command: weechat

parts:
  weechat:
    plugin: x-cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DOPTION_ENABLE_IRC=on
      - -DENABLE_PYTHON=off
      - -DENABLE_IRC=on
    source: https://github.com/lheckemann/weechat.git
    source-type: git
    source-branch: libdir-env
    stage-packages:
      - libcurl3-gnutls:armhf
